# Generated by Django 4.0.2 on 2022-03-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_iteams_iteam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteams',
            name='res',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='res_iteam', to='api.restaurant'),
            preserve_default=False,
        ),
    ]
